#ifndef VENDOR_MAP_HPP
#define VENDOR_MAP_HPP

#include <map>
#include <string>

// TODO: Погуглить разнцу std::string и std::string_view
const std::map<std::string, std::string_view> VENDOR_MAP{
    {"1E4A", "2CRSI SA"},
    {"1DA0", "3M Company"},
    {"1F84", "45Drives Ltd."},
    {"1872", "A &amp; D Company, Ltd."},
    {"1D28", "Aava Mobile Oy"},
    {"1D92", "Abaco Systems Inc."},
    {"13DE", "ABB AB"},
    {"1C85", "ABLIC Inc."},
    {"1F60", "ACCELECOM LTD."},
    {"1FF1", "Accordance Systems Inc."},
    {"1113", "Accton Technology Corporation"},
    {"14D6", "Accusys Storage LTD."},
    {"18E4", "Acer Inc."},
    {"1C94", "Aces Electronics Co., Ltd."},
    {"1B59", "Achronix Semiconductor"},
    {"1DE8", "Acqiris SA"},
    {"1C2A", "Acromag, Inc"},
    {"1DE2", "Action Star Technology Co., Ltd."},
    {"4153", "Active Silicon, Ltd."},
    {"1CC1", "ADATA Technology Co., Ltd."},
    {"15B8", "ADDI-DATA Gmbh"},
    {"144A", "ADLINK Technology"},
    {"1E9C", "Adnacom Inc."},
    {"AD5A", "Adtran Networks SE"},
    {"1022", "Advanced Micro Devices, Inc."},
    {"1CA9", "Advanced-Connectek USA Inc."},
    {"130F", "Advanet, Inc."},
    {"13FE", "Advantech Co., Ltd."},
    {"1850", "Advantest Corporation"},
    {"1D7C", "Aerotech Inc"},
    {"1CF6", "Aetina Corporation"},
    {"1B76", "AIC Inc."},
    {"1447", "AIM GmbH"},
    {"4149", "AIMOTIVE Kft."},
    {"1F41", "AIO Core Co., Ltd."},
    {"1D05", "AIstone Global Limited"},
    {"F1D0", "AJA Video"},
    {"1F98", "Akeana, Inc."},
    {"1F08", "Akrostar Technology Co., Ltd."},
    {"1C0B", "Alazar Technologies, Inc."},
    {"1DED", "Alibaba (China) Co., Ltd."},
    {"204B", "Alignment Engine Inc."},
    {"1B49", "ALLDIS Computersystem GmbH"},
    {"1259", "Allied Telesis Inc."},
    {"194F", "Allion Labs, Inc."},
    {"1D67", "Alltop Technology Co., Ltd"},
    {"1F6D", "Allwinner Technology Co., Ltd."},
    {"4144", "Alpha Data Parallel Systems Ltd."},
    {"1E5C", "Alphawave IP"},
    {"AD00", "Alta Data Technologies"},
    {"1D0F", "Amazon"},
    {"101E", "AMI US Holdings, Inc."},
    {"1DEF", "Ampere Computing, LLC"},
    {"18F8", "Amphenol Corp."},
    {"1A4C", "Amulet Hotkey Ltd."},
    {"1BFB", "Analog Bits"},
    {"11D4", "Analog Devices International"},
    {"12D6", "Analogic Corporation"},
    {"1B12", "Analogix Semiconductor"},
    {"1FFB", "Anduril Industries, Inc."},
    {"27D1", "Angelbird Technologies GmbH"},
    {"12DB", "Annapolis Micro Systems, Inc."},
    {"1852", "Anritsu Corporation"},
    {"19EC", "ANSYS, Inc."},
    {"1BCD", "Apacer Technology Inc."},
    {"1D22", "Apollo Autonomous Driving USA LLC"},
    {"106B", "Apple Computer"},
    {"5554",
     "Applied Research Laboratories, The University of Texas at Austin"},
    {"1EF8", "APTIV"},
    {"1FA7", "Arcanum Advanced Inc."},
    {"17D3", "Areca Technology Corporation"},
    {"13E6", "ARGOSY RESEARCH INC."},
    {"3475", "Arista Networks, Inc."},
    {"1AA1", "Aristocrat Technologies Australia Pty Ltd."},
    {"13B5", "ARM Ltd."},
    {"1E17", "Arnold &amp; Richter Cine Technik GmbH &amp; Co. Betriebs KG"},
    {"1792", "Artiza Networks, Inc."},
    {"125B", "ASIX Electronics Corp."},
    {"1A03", "ASPEED Technology Inc."},
    {"1E5D", "ASR Microelectronics Co., Ltd."},
    {"1C18", "ASSET InterTech, Inc."},
    {"1DFA", "Astera Labs, Inc."},
    {"11BF", "ASTRODESIGN, Inc."},
    {"1A61", "Astron Connectivity Co., Ltd."},
    {"1BD0", "Astronics Corporation"},
    {"1043", "Asustek Computer Inc."},
    {"1DB2", "ATP Electronics, Inc."},
    {"1BDD", "Atrust Computer Corp."},
    {"8024", "Audient Limited"},
    {"175C", "AudioScience, Inc."},
    {"0A7C", "Aurora Innovation Opco, Inc."},
    {"1D50", "Aurotek Corporation"},
    {"1DD7", "AVAL DATA Corporation"},
    {"1AC2", "Avalue Technology Inc."},
    {"2062", "Avaneidi SpA"},
    {"1F3C", "Avant Technology"},
    {"1461", "AVerMedia Technologies, Inc."},
    {"1244", "AVM Audiovisuelles Marketing und Computersysteme GmbH"},
    {"1B08", "Avnet Embedded GmbH"},
    {"1F9D", "Axelera AI B.V."},
    {"1A15", "Axell Corporation"},
    {"1E6B", "Axiado Corporation"},
    {"1EF0", "Ayar Labs"},
    {"1A3B", "AzureWave Technologies, Inc."},
    {"1D84", "b-plus technologies GmbH"},
    {"0BAE", "Bachmann electronic GmbH"},
    {"1B9F", "BAE Systems"},
    {"1D39", "Baikal Electronics, JSC (*Suspended)"},
    {"4D56", "Balluff MV GmbH"},
    {"13CC", "Barco, Inc."},
    {"2013", "Barrie Technology Co., Ltd."},
    {"1AE8", "Basler AG"},
    {"1217", "BayHub Technology Inc"},
    {"17CE", "BCM Advanced Research"},
    {"1FAF", "BCOM Networks Limited"},
    {"1C2F", "Beckhoff Automation GmbH &amp; Co. KG"},
    {"2026", "BedRock Systems, Inc."},
    {"1024", "Beijing Dajia Internet Information Technology Co., Ltd."},
    {"1FE1", "BEIJING ESWIN COMPUTING TECHNOLOGY CO., LTD."},
    {"1FF8", "Beijing Gengtu Technology Co.Ltd"},
    {"205B", "Beijing Henghuizhixun Technology Co., Ltd."},
    {"1C5F", "Beijing Memblaze Technology Co. Ltd."},
    {"9D32", "Beijing Starblaze Technology Co., LTD"},
    {"205E", "Beijing Sudo Information Technology Co., Ltd"},
    {"8088", "Beijing Wangxun Technology Co., Ltd."},
    {"1C75", "Bellwether Electronic Corp."},
    {"1B05", "Benchmark Electronics, Inc."},
    {"3442", "Bihl + Wiedemann GmbH"},
    {"1565", "BIOSTAR MICROTECH INTERNATIONAL CORP."},
    {"1A11", "BitifEye Digital Test Solutions GmbH"},
    {"1DEE", "Biwin Storage Technology Co., Ltd."},
    {"7248", "BizLink Technology, Inc."},
    {"1EF1", "Black Sesame Technologies Co., Ltd."},
    {"1C05", "Blackberry QNX"},
    {"BDBD", "Blackmagic Design Pty Ltd"},
    {"1E38", "Blaize"},
    {"00BB", "Bloombase"},
    {"00B0", "Blue Origin, LLC"},
    {"16F2", "Bosch Rexroth AG"},
    {"1E7C", "Brainchip, Inc."},
    {"9D68", "Brite Semiconductor (Shanghai) Corporation, Ltd."},
    {"1166", "Broadcom Limited"},
    {"1C4F", "Bruker Corporation"},
    {"1154", "Buffalo Inc."},
    {"1B61", "Byd Precision Manufacture Co.,Ltd"},
    {"9000", "C*Core Technology Co., Ltd."},
    {"1F18", "c-payne GmbH"},
    {"1E3A", "Cactus Technologies, Limited"},
    {"17CD", "Cadence Design Systems"},
    {"202C", "CAEN S.p.A."},
    {"CABC", "Cambricon Technologies Corporation Limited"},
    {"11AC", "Canon, Inc."},
    {"197D", "Cap Co., Ltd."},
    {"1F1E", "CARIAD SE"},
    {"1C96", "Carina System Co., Ltd."},
    {"1F8B", "Carl Zeiss Meditec AG"},
    {"1E97", "Caswell Inc."},
    {"1DFD", "CDSG"},
    {"1F7B", "CELESTIAL AI INC"},
    {"18D4", "Celestica"},
    {"123C", "CENTURY SYSTEMS Co.,Ltd."},
    {"F117", "Cerio"},
    {"10DC", "CERN"},
    {"270F", "CHAINTECH Technology Corp."},
    {"1F20", "Channel Well Technology Co., Ltd."},
    {"1CEE", "Chant Sincere Co., Ltd."},
    {"1425", "Chelsio Communications"},
    {"207B", "Cheng Uei Precision Industry Co., Ltd"},
    {"D20C", "Chengdu BeiZhongWangXin Technology Co., Ltd."},
    {"1D94", "Chengdu Higon Integrated Circuit Design Co., Ltd."},
    {"207D", "Chengdu Hurray Data Technology Co., Ltd."},
    {"1EA5", "Chief Land Electronic Co., Ltd."},
    {"1FFE", "Chongqing SeekWave Technology Co., Ltd."},
    {"2080", "Chongqing Shuang Yi Precision Electronic Co., Ltd"},
    {"17E8", "Chrontel, Inc."},
    {"1FF6", "Chunghwa Precision Test Tech. Co., Ltd."},
    {"1A43", "Chuo Electronics Co., Ltd."},
    {"1D47", "Ciena Corporation"},
    {"1013", "Cirrus Logic, Inc."},
    {"1137", "Cisco Systems, Inc."},
    {"C5EC", "Citadel Securities LLC"},
    {"1F6C", "CIX Technology (Shanghai) Co., Ltd"},
    {"1F6C", "CIX Technology Group Co., Ltd"},
    {"04DB", "CLEVER INFORMATION INC."},
    {"1558", "Clevo Co."},
    {"1EE6", "Clientron Corp."},
    {"5853", "Cloud Software Group"},
    {"5853", "Cloud Software Group"},
    {"1FEC", "Clourney Semiconductor"},
    {"CCDE", "Code Construct Pty Ltd"},
    {"12B7", "Cognex Corporation"},
    {"1FE7", "Coherent Inc."},
    {"1830", "Cohu, Inc."},
    {"15D7", "Collins Aerospace"},
    {"1D38", "Colorado Engineering Inc."},
    {"1E9B", "CoMira Solutions Inc"},
    {"1DE6", "Communication Automation Corporation"},
    {"14C0", "Compal Electronics, Inc."},
    {"1C69", "Comtel Electronics GmbH"},
    {"1A2F", "congatec GmbH"},
    {"12C4", "Connect Tech Inc."},
    {"1F81", "CONNPRO ind."},
    {"1221", "Contec Co., Ltd."},
    {"1E48", "Continental Autonomous Mobility Germany GmbH"},
    {"2049", "CoreComm Technology Co., Ltd."},
    {"1DA8", "Corigine Inc."},
    {"1E8A", "Cornami, Inc."},
    {"434E", "Cornelis Networks, Inc."},
    {"1CFA", "Corsair Memory, Inc"},
    {"136C", "CPI Technologies, Inc."},
    {"1102", "Creative Technology Ltd"},
    {"1E23", "Credo Semiconductor, Inc."},
    {"CCEC", "Curtiss-Wright Defense Solutions"},
    {"200B", "Cyan Semiconductor Co.Ltd."},
    {"1F82", "d-Matrix Corporation"},
    {"1E7D", "Daichu Technologies Co.,Ltd."},
    {"19EB", "DAIHEN Corporation"},
    {"1BFA", "Daiichi Jitsugyo Viswill Co., Ltd"},
    {"1C33", "Daktronics, Inc."},
    {"194A", "Dap Holding B.V."},
    {"1E3B", "DapuStor Corporation"},
    {"1E1A", "DataDirect Networks, Inc."},
    {"1FF4", "DEEPX Co., Ltd."},
    {"1F0D", "DeGirum Corporation"},
    {"1A0E", "DekTec Digital Video B.V."},
    {"1E33", "Delkin Devices"},
    {"1028", "Dell Computer Corporation"},
    {"1DF2", "Delphi Engineering Group, Inc."},
    {"1A05", "Delta Electronics, Inc."},
    {"1B66", "Deltatec"},
    {"1192", "Densan Co., Ltd."},
    {"1FFF", "DENSO Corporation"},
    {"1D78", "Dera co., Ltd."},
    {"2041", "Dexerials Corporation"},
    {"15BD", "DFI Inc."},
    {"1369", "Digigram"},
    {"DD01", "Digital Devices"},
    {"18FD", "Digital Media Professionals, Inc."},
    {"12D8", "Diodes Incorporated"},
    {"119D", "DMG MORI Digital Co., LTD."},
    {"11C8", "Dolphin Interconnect Solutions AS"},
    {"1E82", "Dongguan Yizhao Electronic Co.,Ltd."},
    {"1E93", "Douyin Vision Co., Ltd."},
    {"1EDE", "DreamBig Semiconductor Inc"},
    {"4453", "dSPACE GmbH"},
    {"1BFC", "duagon AG"},
    {"3100", "Dynabook Inc."},
    {"1197", "DynamicSignals, LLC"},
    {"201E", "E-Semi Electronics CO., LTD."},
    {"1B98", "E.E.P.D. GmbH"},
    {"2076", "EA SEMI (SAHNGHAI) TECH LIMITED"},
    {"177C", "EBRAINS, INC."},
    {"1DD6", "ECRIN SYSTEMS"},
    {"1428", "EDEC Linsey System Co., Ltd."},
    {"1FDC", "EdgeCortix Corporation"},
    {"1ECE", "EdgeQ, Inc."},
    {"1F7A", "Efinix, Inc."},
    {"1F42", "EGK ELECTRONICS TECHNOLOGY LIMITED"},
    {"1DE5", "Eidetic Communications Inc"},
    {"181D", "eInfochips, Inc."},
    {"1227", "EIZO Rugged Solutions"},
    {"E4BF", "EKF Elektronik GmbH"},
    {"13B9", "ELECOM CO LTD"},
    {"202E", "Electric Connector Technology Co., Ltd."},
    {"201C", "Electronic Data Integration Co"},
    {"1C7F", "Elektrobit Austria GmbH"},
    {"1D4B", "Elektrosfera LTD."},
    {"1019", "Elitegroup Computer Systems Inc."},
    {"2079", "Elka International Ltd."},
    {"1C24", "Elma Electronic Inc"},
    {"2068", "EmBestor Technology Inc."},
    {"1E5E", "Emergent Vision Technologies Inc"},
    {"1EBD", "EMERGETECH Company Ltd."},
    {"EA50", "Emerson Automation Solutions"},
    {"2027", "EnCharge AI, Inc."},
    {"EACE", "Endace Technology Ltd."},
    {"EFAB", "Enfabrica Corporation"},
    {"123D", "Engineering Design Team, Inc."},
    {"1FF5", "Enginetech Computer Information Co.,Ltd"},
    {"200A", "Enosemi, Inc."},
    {"1FBD", "Enrigin Technology (Xiamen) Co., Ltd."},
    {"2054", "Eoptolink Technology Inc.Ltd."},
    {"165A", "EPIX, INC."},
    {"1A25", "Ericsson AS"},
    {"12FE", "esd electronics gmbh"},
    {"1E45", "ESSENCORE Limited"},
    {"1F43", "Ethernovia Inc."},
    {"1977", "Etion Create (Pty) Ltd."},
    {"1EC2", "eTopus Technology Inc."},
    {"1B6F", "Etron Technology, Inc."},
    {"1805", "Euresys SA"},
    {"2012", "EverPro Technology Company Limited"},
    {"1D86", "Evertz Microsystems Ltd."},
    {"4556", "Evident Corporation"},
    {"1F8C", "Exascend, Inc."},
    {"1D8F", "EXEGY"},
    {"1BC1", "EXFO Inc."},
    {"1E05", "Exicon Co., Ltd."},
    {"2071", "EXPERT INTERNATIONAL MERCANTILE CORPORATION"},
    {"1CAD", "EXTOLL GmbH"},
    {"5845", "Extreme Engineering Solutions"},
    {"F5F5", "F5 Networks, Inc."},
    {"1FFC", "Fabric of Truth, Inc"},
    {"1D9B", "Facebook"},
    {"1DC5", "FADU Inc."},
    {"188B", "Faraday Technology Corporation"},
    {"1463", "Fast Corporation"},
    {"190E", "Fidus Systems Inc."},
    {"1E1B", "Firm INFORMTEST Ltd.(*Suspended)"},
    {"2033", "FLC Technology Group Inc."},
    {"1895", "Flextronics International"},
    {"1EFB", "Flexxon Pte Ltd"},
    {"1CB5", "Focusrite Audio Engineering Ltd"},
    {"1778", "For-A Company Limited"},
    {"1F6A", "Ford Motor Company"},
    {"1165", "Foresight Imaging LLC"},
    {"1796", "Forschungszentrum Jülich GmbH"},
    {"1A29", "Fortinet, Inc."},
    {"1FF3", "ForwardEdge ASIC, LLC."},
    {"105B", "Foxconn (Hon Hai)"},
    {"F111", "Framework Computer Inc."},
    {"1F79", "Fraunhofer Institute for Industrial Mathematics (ITWM)"},
    {"2052", "Frontgrade Gaisler AB"},
    {"1FF7", "FSP Technology Inc."},
    {"16EA", "Fuji Electric Co., Ltd."},
    {"1135", "FUJIFILM Business Innovation Corp."},
    {"1183", "Fujikura Ltd."},
    {"10CF", "Fujitsu Limited"},
    {"1AAA", "Furukawa ElectricCo., Ltd."},
    {"10B0", "Gainward Technology Int&#039;l Limited"},
    {"1B4C", "Galaxy Microsystems Ltd."},
    {"1775", "GE Aviation"},
    {"1FB8", "GE HealthCare Technologies Inc"},
    {"1DD2", "GE-Creative co., Ltd.  ( I-Cube Technology Division )"},
    {"17F9", "GemTek Technology Co., Ltd."},
    {"0123", "General Dynamics Mission Systems, Inc."},
    {"1D32", "Genesis Co.,Ltd"},
    {"17A0", "Genesys Logic, Inc."},
    {"15E7", "GET Engineering Corporation"},
    {"165C", "Gidel Ltd."},
    {"1458", "Giga-Byte Technology Co., Ltd."},
    {"206D", "GigaIO Networks, Inc."},
    {"2006", "GinMeta Co., LTD"},
    {"1F88", "GL Communications Inc."},
    {"6766", "Glenfly Tech Co., Ltd."},
    {"ECAB", "GM Cruise LLC"},
    {"140E", "GOEPEL electronic GmbH"},
    {"1D2D", "Good Way Technology Co., Ltd."},
    {"1AE0", "Google, Inc."},
    {"1A83", "Gopher Inc."},
    {"1C5E", "GopherTec Inc."},
    {"2008", "GoPro"},
    {"22C2", "Gowin Semiconductor Corporation"},
    {"1EF6", "GrAI Matter Labs"},
    {"2072", "Grandtrans Communication (Zhejiang) Co., Ltd."},
    {"1BD7", "Granite River Labs Inc."},
    {"1D95", "Graphcore Ltd"},
    {"1B95", "Green Hills Software"},
    {"1BF5", "Greenliant"},
    {"1DE0", "Groq, Inc."},
    {"1E4C", "GSI Technology"},
    {"6688", "GUANGZHOU MAXSUN INFORMATION TECHNOLOGY CO., LTD."},
    {"1FEB", "Guangzhou Zhiyuan Electronics Co., Ltd"},
    {"2046", "GXMICRO Technology (shanghai) CO.,LTD"},
    {"1D29", "Hagiwara Solutions Co., Ltd."},
    {"1E60", "HAILO Technologies LTD."},
    {"11A1", "Hamamatsu Photonics K.K."},
    {"1F83", "Hangzhou Clounix Technology Limited"},
    {"0823", "Hangzhou Hongjun Microelectronics Co., Ltd."},
    {"202F", "Hangzhou Kanxin Technology Co., Ltd"},
    {"1D0E", "HARTING Electronics GmbH"},
    {"112B", "Heidelberger Druckmaschinen AG"},
    {"1E85", "Heitec AG"},
    {"203F", "Henan KunLun Technologies Co., Ltd."},
    {"1ACD", "Hensoldt Sensors GmbH"},
    {"78C0", "Herrick Technology Laboratories (HTL), Inc."},
    {"1590", "Hewlett Packard Enterprise"},
    {"1C55", "Hexagon Metrology S.P.A."},
    {"1FB4", "HEXIN Technologies Co., Ltd."},
    {"1103", "HighPoint Technologies, Inc."},
    {"15CF", "Hilscher Gesellschaft fuer Systemautomation mbH"},
    {"1FCD", "Hitachi High-Tech Corporation"},
    {"1250", "Hitachi Solutions Technology, Ltd."},
    {"1367", "Hitachi Zosen Corporation"},
    {"1054", "Hitachi, Ltd."},
    {"2067", "Hitachi-LG Data Storage, Inc."},
    {"14A9", "Hivertec, Inc."},
    {"204E", "HKC Shilian (Shenzhen) Electronics Co., Ltd"},
    {"1BEE", "HMS Technology Center GmbH"},
    {"10AC", "Honeywell Inc."},
    {"1F37", "Hongkong Likfo (China) Business LTD"},
    {"1EE7", "Honor Device Co., Ltd."},
    {"2033", "Hosiden Corporation"},
    {"103C", "HP Inc."},
    {"1E83", "Huaqin Technology Co.Ltd"},
    {"19E5", "Huawei Technologies Co., Ltd."},
    {"2063", "Hubei Yangtze Mason Semiconductor Technology Co., Ltd."},
    {"200E", "HYVE Solutions"},
    {"10FC", "I-O Data Device, Inc."},
    {"18F2", "I-PEX (Dai-ichi Seiko)"},
    {"1AAC", "IBASE Technology Inc."},
    {"11CA", "IBEX Technology, Co. Ltd."},
    {"1014", "IBM"},
    {"1FBC", "ICR, Inc."},
    {"1B53", "iD corporation"},
    {"180C", "IEI Integration Corp."},
    {"1BD4", "IEIT SYSTEMS Co., Ltd."},
    {"1C9D", "Illumina"},
    {"1FF9", "Inagile  Electronic Technology Co., LTD"},
    {"15D1", "Infineon Technologies AG"},
    {"202A", "InfiniLink Inc."},
    {"1EDA", "infodas GmbH"},
    {"2035", "InfoKey Vault Technology Co., Ltd."},
    {"1F1D", "Initio (HK) Corporation Limited"},
    {"1BC0", "InnoDisk Corporation"},
    {"1DBE", "Innogrit Corporation"},
    {"2029", "Innolight Technology USA Inc."},
    {"1EC8", "INNOSILICON MICROELECTRONICS (wuhan)"},
    {"1CFB", "Innotech Corporation"},
    {"1771", "InnoVision Multimedia, Ltd."},
    {"2032", "Inova Semiconductors GmbH"},
    {"2030", "Inspur Academy of Science and Technology"},
    {"2039", "Inspur Computer Technology Co., Ltd."},
    {"1D4D", "Integrated Design Tools, Inc."},
    {"1E99", "INTEGRATED SERVICE TECHNOLOGY Inc."},
    {"203D", "INTEKPLUS Co., Ltd."},
    {"8086", "Intel Corporation"},
    {"2021", "Intelligent Memory Limited"},
    {"1739", "Interface Concept"},
    {"1147", "Interface Corporation"},
    {"1A6E", "International Game Technology"},
    {"1E12", "Introspect Technology"},
    {"7548", "INUITIVE LTD."},
    {"1170", "Inventec Corporation"},
    {"5353", "iodyne"},
    {"1546", "IOI Technology Corporation"},
    {"1F04", "iPasslabs Technology Co. Ltd."},
    {"1E6A", "IRISO Electronics Co., Ltd"},
    {"1283", "ITE Tech. Inc."},
    {"2050", "ITI Engineering, LLC"},
    {"5AB7", "IXI Technology"},
    {"1F8A", "J-Squared Technologies Inc."},
    {"10D3", "Jabil Circuit Inc."},
    {"2073", "Jacobs Special Products Division"},
    {"1817", "JAE"},
    {"1F72", "Jane Street Group, LLC"},
    {"13C3", "Janz Tec AG"},
    {"1D12", "JESS-LINK PRODUCTS CO., LTD."},
    {"2038", "Jiangsu FuHao Electronic Science and technology CO.,LTD."},
    {"1E7F", "Jiangsu Huacun Electronic Technology Co., Ltd."},
    {"1EEC", "Jiangsu Viscore Technologies Co.,Ltd"},
    {"2025", "Jiangxi Firefly Microelectronics Technology Co., Ltd"},
    {"206B", "Jingdong Technology Information Technology Co., Ltd."},
    {"197B", "JMicron Technology Corporation"},
    {"1C65", "Jump Trading Group"},
    {"1304", "Juniper Networks"},
    {"206E", "JWIPC TECHNOLOGY CO., LTD."},
    {"200D", "K-tronics(Suzhou) Technology Co., LTD"},
    {"18B2", "K.K. Rocky"},
    {"1D26", "KALRAY"},
    {"1E6F", "Kandou Bus S.A."},
    {"13A1", "Kawasaki Heavy Industries, Ltd."},
    {"CEBA", "KEBA Industrial Automation GmbH"},
    {"1A3F", "KEL Corporation"},
    {"1B2A", "Keyence Corporation"},
    {"15BC", "Keysight Technologies"},
    {"2020", "KEYSTONE MICROTECH CORPORATION"},
    {"1E58", "Kinara Inc."},
    {"2646", "Kingston Technology Company"},
    {"1E0F", "Kioxia Corporation"},
    {"1BBA", "KLA-Tencor"},
    {"1FA9", "Knowledge Development for Rugged Optical Communications (KDROC)"},
    {"1059", "Kontron"},
    {"207C", "Korea Electric Terminal Co., Ltd."},
    {"1FDE", "Kratos Defense &amp; Security Solutions, Inc."},
    {"2057", "Kunlunxin (Beijing) Technology Co., Ltd"},
    {"1A07", "Kvaser AB"},
    {"1893", "Kyocera Corporation"},
    {"1738", "L3Harris Technologies, Inc."},
    {"1D71", "Laird Connectivity, LLC"},
    {"1204", "Lattice Semiconductor Corporation"},
    {"2031", "Lauterbach GmbH"},
    {"107D", "Leadtek Research Inc."},
    {"2066", "Leason Technology Co., Ltd"},
    {"1F74", "Leica Camera AG"},
    {"2074", "Leidos Inc."},
    {"17AA", "Lenovo"},
    {"1F50", "LeRain Technology Co., Ltd"},
    {"1854", "LG Electronics"},
    {"1E29", "LIBERTRON Co., Ltd."},
    {"060E", "Lightelligence, Inc."},
    {"1ECA", "Lightmatter"},
    {"2058", "Lime Microsystems Ltd"},
    {"1FF2", "LinkData Technology (Tianjin) Co., LTD"},
    {"4C52", "Linkreal Co., Ltd."},
    {"1D14", "Lintes Technology Co., Ltd."},
    {"2040", "LINX Corporation"},
    {"1DCD", "Liqid Inc"},
    {"4C4D", "Liquid-Markets GmbH"},
    {"1F13", "Listan GmbH"},
    {"4C54", "Lisuan Technology Co., Ltd."},
    {"14A4", "Lite-On Technology Corporation"},
    {"2032", "lnova Semiconductors GmbH"},
    {"1784", "Lockheed Martin"},
    {"1DBD", "Logic Fruit Technologies Pvt Ltd"},
    {"207F", "Lontium Semiconductor Corporation"},
    {"0014", "Loongson Technology Corporation Limited"},
    {"1880", "LOTES Co., Ltd"},
    {"1BDF", "LUXSHARE-ICT, Inc."},
    {"1CAB", "Lynx Software Technologies, Inc."},
    {"1E9F", "Lynxi Technologies Ltd., Co."},
    {"1D27", "M31 Technology Corporation"},
    {"1916", "Macnica, Inc."},
    {"2337", "Macronix International Co., Ltd."},
    {"1E65", "Magic Leap, Inc"},
    {"1F52", "MangoBoost Inc."},
    {"137A", "Mark of the Unicorn, Inc."},
    {"1DCA", "Marvell Semiconductor, Inc."},
    {"16E2", "Marvin Test Solutions, Inc."},
    {"102B", "Matrox Graphics Inc."},
    {"1E43", "MaxLinear Inc"},
    {"1DD0", "McDowell Signal Processing, LLC"},
    {"1AA2", "Media Links Co., LTD."},
    {"14C3", "MediaTek Incorporation"},
    {"1E39", "MEDION AG"},
    {"10A0", "Meidensha Corporation"},
    {"1360", "Meinberg Funkuhren GmbH &amp; Co. KG"},
    {"152E", "Melec Inc."},
    {"2060", "MEMKOR Inc"},
    {"1FE9", "MemryX Corp"},
    {"1E2E", "Mercedes-Benz R&amp;D North America, Inc."},
    {"1FBB", "Meritech Co., Ltd."},
    {"9999", "MetaX Integrated Circuits (Shanghai) Co., Ltd."},
    {"1462", "Micro-Star International Co., Ltd."},
    {"11F8", "Microchip Technology"},
    {"1344", "Micron Technology, Inc."},
    {"1414", "Microsoft"},
    {"4D54", "Microtechnica Co., Ltd."},
    {"1322", "MIS Corporation"},
    {"22DB", "Missing Link Electronics, Inc."},
    {"1DAF", "MIT Lincoln Laboratory"},
    {"1071", "MiTAC International Corporation"},
    {"10BA", "Mitsubishi Electric Corporation"},
    {"1547", "Mitutoyo Corporation"},
    {"1C8C", "Mobiveil, Inc."},
    {"10D2", "Molex LLC"},
    {"1FA5", "Monolithic Power Systems"},
    {"2022", "Monster Computer Technology Inc."},
    {"1B00", "Montage Technology Co., Ltd."},
    {"1AFD", "Moog Inc."},
    {"2016", "Motional AD Inc"},
    {"1F0A", "Motorcomm Electronic Technology Co.,Ltd"},
    {"1155C", "MOVE.B"},
    {"203A", "MPI CORPORATION"},
    {"18E6", "MPL AG"},
    {"2017", "Mujin, Inc."},
    {"1ED9", "Myrtle.ai"},
    {"1CD7", "Nanjing Magewell Electronics Co., Ltd."},
    {"1C00", "Nanjing Qinheng Microelectronics Co., Ltd."},
    {"1B8F", "Nanoteq (Pty) Ltd"},
    {"203C", "NANOWELL INFO TECH CO., LIMITED"},
    {"18F4", "Napatech AS"},
    {"1093", "National Instruments Corporation"},
    {"1B4E", "Nations Technologies Inc."},
    {"1EBB", "nCipher Security Ltd"},
    {"1F0F", "Nebula Matrix"},
    {"1BCF", "NEC"},
    {"1E9A", "Neoconix"},
    {"1D85", "Neosem Holdings Inc"},
    {"1F40", "Netac Technology Co.,Ltd"},
    {"1275", "NetApp, Inc."},
    {"1D82", "NETINT Technologies Inc."},
    {"1C1B", "Netlist, Inc."},
    {"203E", "Netprisma Inc."},
    {"19EE", "Netronome"},
    {"1FA1", "Neubla Korea"},
    {"1FD9", "Neuchips Inc."},
    {"1F49", "NeuReality LTD"},
    {"1E73", "NeuroBlade"},
    {"193D", "New H3C Technologies Co., Ltd."},
    {"AD10", "New Wave Design and Verification, LLC"},
    {"1EA4", "Newtech Co., Ltd."},
    {"1EBC", "Nexark, Inc DBA Sabrent"},
    {"1933", "Nexcom International"},
    {"1B07", "NEXTCHIP Co,Ltd"},
    {"19D4", "Nexteq Plc"},
    {"1F31", "Nextorage Corporation"},
    {"CDFA", "NextSilicon Ltd"},
    {"1F86", "NEXTY Electronics Corporation"},
    {"11DF", "Nexus Technology, Inc."},
    {"1BB2", "Nikon Corporation"},
    {"12E1", "Nintendo Co., Ltd."},
    {"202D", "Nitto Denko Corporation"},
    {"13B8", "Nokia Solutions and Networks Oy"},
    {"1B0C", "Northrop Grumman Corp., Electronic Systems"},
    {"0222", "Not for Radio, LLC"},
    {"1CBD", "Novachips Co., Ltd"},
    {"1D37", "NovaSparks"},
    {"1E09", "Novatek Microelectronics Corporation"},
    {"1646", "NSW Inc."},
    {"12A4", "NTT Innovative Devices Corporation"},
    {"1F0B", "Nubis Communications, Inc."},
    {"4E58", "Nutanix, Inc."},
    {"1050", "Nuvoton Technology Israel"},
    {"1808", "nVent, Schroff GmbH"},
    {"10DE", "NVidia Corporation"},
    {"1131", "NXP Semiconductors"},
    {"16C8", "Octasic Inc."},
    {"1795", "OKB SAPR"},
    {"1021", "Oki Electric Industry Co., Ltd."},
    {"1270", "Olympus Corporation"},
    {"012E", "OLZETEK"},
    {"201A", "OMNIVA"},
    {"10CB", "Omron Corporation"},
    {"160C", "OMS Motion, Inc."},
    {"1954", "One Stop Systems, Inc."},
    {"1E03", "OnLogic, Inc."},
    {"1BD9", "Open Text Corporation"},
    {"2077", "OpenAI OpCo LLC"},
    {"18FE", "Opex Corporation"},
    {"206C", "OPTALYSYS LIMITED"},
    {"148A", "OPTO 22"},
    {"108E", "Oracle Corporation"},
    {"1DA4", "Orient Semiconductor Electronics, Ltd."},
    {"1576", "Osprey Video"},
    {"169A", "Otari, Inc."},
    {"1C7A", "Other World Computing"},
    {"19A4", "Owl Cyber Defense Solutions LLC"},
    {"1E59", "Oxford Nanopore Technologies plc"},
    {"01DE", "Oxide Computer Company"},
    {"2082", "P-TWO INDUSTRIES INC."},
    {"1569", "Palit Microsystems Ltd."},
    {"1EAF", "Palo Alto Networks"},
    {"1189", "Panasonic Holdings Corporation"},
    {"0815", "Panmnesia, Inc."},
    {"1AF8", "Parade Technologies, Inc."},
    {"1AB8", "Parallels International GmbH"},
    {"1DDB", "Parraid, LLC"},
    {"2015", "Pascaline Systems, Inc."},
    {"204C", "PAX ANDROMEDA"},
    {"174B", "PC Partner Limited"},
    {"001C", "PEAK-System Technik GmbH"},
    {"1B0A", "Pegatron Corporation"},
    {"1EFE", "Peng Yu Trigold Limited"},
    {"1EE4", "PetaIO Inc."},
    {"9753", "PEZY Computing K.K."},
    {"1987", "Phison Electronics Corporation"},
    {"1442", "Phoenix Contact Electronics GmbH"},
    {"1363", "Phoenix Technologies"},
    {"115C", "Photron Limited"},
    {"1761", "Pickering Interfaces Ltd."},
    {"1EE2", "plc2 Design GmbH"},
    {"1E7E", "PLIOPS LTD."},
    {"1D7F", "Plugable"},
    {"15BB", "Portwell, Inc."},
    {"0CCD", "Preferred Networks, Inc."},
    {"2056", "Prodapt ASIC Services"},
    {"1C72", "ProDesign Electronic GmbH"},
    {"1D13", "Prodigy Technovations Private Limited"},
    {"1D33", "Prodrive Technologies"},
    {"105A", "Promise Technology, Inc."},
    {"19D5", "Protech Systems"},
    {"17C3", "Protogate, Inc."},
    {"1D00", "Pure Storage, Inc."},
    {"1F33", "Purplelec Inc.Co.,Ltd"},
    {"1BAA", "QNAP Systems, Inc."},
    {"1E34", "Qrypt, Inc."},
    {"1A9D", "QSC LLC"},
    {"17CB", "Qualcomm Incorporated"},
    {"1F70", "Qualitas Semiconductor Co., Ltd."},
    {"152D", "Quanta Computer Inc."},
    {"1F90", "QUSIDE TECHNOLOGIES S.L."},
    {"1E81", "Ramaxel Technology (Shenzhen) Limited"},
    {"19AA", "Rambus Inc."},
    {"1F1F", "Ranovus Inc."},
    {"1DE4", "Raspberry Pi (Trading) Limited"},
    {"1195", "Ratoc Systems Inc."},
    {"1E92", "Raymax Technology Ltd."},
    {"10B2", "Raytheon Company"},
    {"17F3", "RDC Semiconductor Co., Ltd."},
    {"10EC", "Realtek Semiconductor Corporation"},
    {"1EFF", "Rebellions Inc."},
    {"1BAD", "REFLEX CES"},
    {"1960", "REJ Co., Ltd."},
    {"1912", "Renesas Electronics Corporation"},
    {"163F", "Renishaw plc."},
    {"1180", "Ricoh Company, Ltd."},
    {"22A2", "RIGOL TECHNOLOGIES CO., LTD."},
    {"1B2E", "Riverbed Technology, Inc."},
    {"1EFD", "Rivos Inc"},
    {"1D18", "RME GmbH"},
    {"1D87", "Rockchip Electronics Co., Ltd."},
    {"12A0", "Rockwell Automation Inc. (Allen-Bradley)"},
    {"162F", "ROHDE &amp; SCHWARZ GmbH &amp; Co. KG"},
    {"10DB", "Rohm Co., Ltd."},
    {"16CE", "Roland Corporation"},
    {"1F5B", "Roscoe Software LLC"},
    {"1F62", "Rosenberger Hochfrequenztechnik GmbH &amp; Co.KG"},
    {"1CBF", "Ross Video"},
    {"1435", "RTD Embedded Technologies, Inc."},
    {"1B86", "Saab AB"},
    {"1EBC", "Sabrent"},
    {"1DD3", "Sage Microelectronics Corp."},
    {"144D", "Samsung Electronics Co., Ltd."},
    {"1A82", "Samtec"},
    {"1923", "Sangoma Technologies Corporation"},
    {"1CC3", "Sanmina"},
    {"1380", "Sanritz Automation Co., Ltd."},
    {"8686", "SAP SE"},
    {"1DA2", "Sapphire Technology Limited"},
    {"2043", "Satel Oy"},
    {"174F", "SAXA, Inc."},
    {"CC53", "ScaleFlux Inc."},
    {"1C2E", "Schneider Electric Japan Holdings Ltd."},
    {"1AA9", "Schweitzer Engineering Labs, Inc."},
    {"1FBE", "ScioTeq bv"},
    {"11C6", "SCREEN GRAPHIC SOLUTIONS CO., LTD."},
    {"1BB1", "Seagate Technology LLC"},
    {"1A0D", "SEAKR Engineering Inc."},
    {"135E", "Sealevel Systems, Inc."},
    {"1BEC", "SECO S.P.A."},
    {"1CDD", "Secunet Security Networks AG"},
    {"11DB", "SEGA CORPORATION"},
    {"14EB", "Seiko Epson Corporation"},
    {"2075", "Semidynamics Technology Services, S.L."},
    {"1F26", "SEMIFIVE, INC."},
    {"1FB1", "Semight Instrument Co.,Ltd."},
    {"18D7", "Semtech Corp"},
    {"1EB9", "Senscomm Semiconductor Co., Ltd."},
    {"1AB1", "Sequans Communications"},
    {"1CB4", "SerialTek"},
    {"1FA4", "Shandong SinoChip Semiconductors Co., Ltd."},
    {"1EDB", "SHANGHAI ANLOGIC INFOTECH CO., LTD."},
    {"1F4F", "Shanghai DaoCloud Network Technology Co., Ltd. (DaoCloud)"},
    {"1E36", "Shanghai Enflame Technology Co. Ltd"},
    {"1E3E", "Shanghai Iluvatar CoreX Semiconductor Co., Ltd."},
    {"2014", "Shanghai Sixunited Intelligent Technology Co., Ltd."},
    {"2065", "Shanghai Varytech Electronics Co., Ltd."},
    {"1F67", "Shanghai Yunsilicon Technology Co,. Ltd."},
    {"1D17", "Shanghai Zhaoxin Semiconductor Co., Ltd."},
    {"205D", "Shanghai Zijing Xinjie Intelligent Technology Co., Ltd."},
    {"1FBA", "Shenglan Technology Co., Ltd."},
    {"8009", "Shengli Technologies Co., Ltd"},
    {"7377", "Shenzhen Colorful Yugong Technology and Development Co., Ltd."},
    {"1F4A", "Shenzhen Corerain Technologies. Co. Ltd."},
    {"1E0B", "Shenzhen Decenta Technology Co.,LTD"},
    {"1D08", "Shenzhen Deren Electronic Co.,Ltd."},
    {"1EB3", "Shenzhen Goodtimes Technology Co.,Ltd"},
    {"1EF7", "Shenzhen Gunnir Technology Development Co., Ltd"},
    {"1F69", "Shenzhen Haocheng Electronic Technology Co., Ltd"},
    {"1FB5", "Shenzhen Huahao Electromechanical Co.,Ltd"},
    {"1F66", "Shenzhen Huahong Intelligence Co,.Ltd."},
    {"1FB0", "Shenzhen ICube Corporation Limited"},
    {"1F53", "Shenzhen Jaguar Microsystems Co.,Ltd."},
    {"2044", "Shenzhen Jiahua Zhongli Technology Co., LTD"},
    {"2010", "Shenzhen Kingspec Electronics Technology Co., Ltd."},
    {"1F55", "Shenzhen MADIGI Electronic Technology Co.,Ltd"},
    {"2045", "Shenzhen Meigaolan Electronic Instrument Co., Ltd."},
    {"2036", "Shenzhen Netforward Microelectronics Co., Ltd"},
    {"1F73", "Shenzhen Quanxing Tech Co., Ltd"},
    {"1F03", "Shenzhen Shichuangyi Electronics Co., Ltd"},
    {"1E87", "Shenzhen Shinning Electronic Co.,Ltd."},
    {"1F99", "Shenzhen Techwinsemi Technology Company Limited"},
    {"1F80", "Shenzhen Tong Tai Yi information Technology Co.,Ltd"},
    {"204D", "Shenzhen Xinxin Semiconductor Co., Ltd."},
    {"2011", "SHENZHENBMORN TECHNOLOGY CO.,LTD"},
    {"1C37", "Shikino High-Tech Co., Ltd"},
    {"1C71", "Shimadzu Corporation"},
    {"1FFA", "SHINKO ELECTRIC INDUSTRIES CO., LTD."},
    {"1EA1", "Sichuan Huafeng Technology Co., Ltd."},
    {"202B", "Sicoya"},
    {"110A", "Siemens AG"},
    {"8510", "Sietium Semiconductor Technology (Shandong) Co., Ltd"},
    {"F15E", "SiFive, Inc."},
    {"17D2", "SigBitz LLC"},
    {"1F45", "Signal Easy Technologies Co., Ltd."},
    {"1BEB", "SignalCore, Inc."},
    {"1F8F", "Signature Ip Corporation"},
    {"131F", "SIIG Inc."},
    {"1BCE", "Silex Technology, Inc."},
    {"1374", "Silicom, Ltd."},
    {"1E14", "Silicon Creations, LLC"},
    {"1F39", "Silicon Innovation Technologies Co., Ltd."},
    {"126F", "Silicon Motion Inc."},
    {"1F06", "SiMa.ai"},
    {"2059", "Simtek Technology Co., Ltd."},
    {"1DF9", "Simula Technology Inc."},
    {"1FE8", "SINGATRON TECHNOLOGY (HONG KONG) CO., LTD"},
    {"205F", "SIPEARL"},
    {"1F87", "SiTime Corp."},
    {"025E", "SK hynix Inc."},
    {"2024", "SkyeChip"},
    {"1543", "Skyworks Solutions, Inc."},
    {"1235", "SMART Modular Technologies"},
    {"1CDF", "SmartDV North America, LLC"},
    {"50C1", "Socionext Inc."},
    {"14A0", "Softing AG"},
    {"1BC9", "Sonifex Ltd"},
    {"104D", "Sony Group Corporation"},
    {"1F1C", "SOPHGO Technologies Ltd."},
    {"1E31", "SORD Corporation"},
    {"201F", "SpacemiT (Hangzhou) Technology Co. Ltd"},
    {"1DAC", "SparkLAN Communications, Inc."},
    {"172F", "Sparkle Computer Co., Ltd."},
    {"18F1", "Spectrum Instrumentation GmbH"},
    {"DA7A", "Speedata Inc."},
    {"174A", "Spirent Communications"},
    {"1A8A", "Star Bridge, Inc."},
    {"1BCA", "Star Communications, Inc."},
    {"1B5E", "Star-Dundee Ltd."},
    {"1B45", "StarTech.com Ltd."},
    {"1683", "StepTechnica Co., Ltd."},
    {"104A", "STMicroelectronics International NV"},
    {"159C", "Stratus Technologies, Inc."},
    {"1349", "Sumitomo Electric Industries, Ltd."},
    {"1FD4", "Sunix Co., Ltd."},
    {"15D9", "Super Micro Computer Inc."},
    {"206A", "Surge Intelligence"},
    {"1EE9", "SUSE LLC"},
    {"2064", "Suzhou Centec Communications"},
    {"1E27", "Suzhou Denglin Technologies Co., Ltd"},
    {"1EE1", "Suzhou Kuhan Information technologies"},
    {"1DD4", "Swissbit AG"},
    {"1E01", "Synaptics, Inc."},
    {"1CA1", "Sync-n-Scale, LLC"},
    {"7053", "Synology Inc."},
    {"16C3", "Synopsys, Inc."},
    {"184B", "SYSTEC Corporation"},
    {"204F", "Taalas Inc"},
    {"1CEB", "Taiwan Pulse Motion Co., Ltd."},
    {"2051", "TARNG YU ENTERPRISE CO., LTD"},
    {"12AF", "TDK Corporation"},
    {"1513", "TE Connectivity"},
    {"1D61", "Technobox, Inc."},
    {"1C4E", "Techway"},
    {"1DA1", "Teko Telecom S.r.l. a Socio Unico"},
    {"1268", "Tektronix"},
    {"1D88", "Telechips Inc."},
    {"8189", "Telecommunications Technology Association"},
    {"11EC", "Teledyne Dalsa"},
    {"1570", "Teledyne LeCroy"},
    {"1B37", "Teledyne SP Devices"},
    {"13E5", "Telesoft Technologies Ltd."},
    {"1C5D", "Telit Communications SPA"},
    {"FE19", "TenaFe Inc."},
    {"1EA0", "Tencent Technology (Shenzhen) Company Limited"},
    {"1E52", "Tenstorrent Inc"},
    {"1316", "Teradyne, Inc."},
    {"204A", "TeraSignal"},
    {"2009", "Terawins, INC."},
    {"751A", "Tesla Inc"},
    {"1498", "TEWS Technologies GmbH"},
    {"104C", "Texas Instruments"},
    {"1269", "Thales"},
    {"1AB5", "The Boeing Company"},
    {"1BD5", "The FreeBSD Foundation"},
    {"1BE9", "The MathWorks, Inc."},
    {"1168", "Thine Electronics, Inc"},
    {"14D2", "TITAN Electronics Inc."},
    {"1679", "Tokyo Electron Device Ltd."},
    {"138B", "TOKYO KEIKI INC."},
    {"1D05", "TONGFANG HONGKONG LIMITED"},
    {"1FAD", "Tongxin Microelectronics Co., Ltd."},
    {"1D45", "Top Victory Investments Limited"},
    {"1FF0", "Toradex AG"},
    {"1179", "Toshiba Corporation"},
    {"15A5", "Toyota Technical Development Corporation"},
    {"1EEE", "Tracewell Systems, Inc."},
    {"1D79", "Transcend"},
    {"2053", "Transchip Technology (Nanjing) Co., Ltd."},
    {"1A3D", "Tritek Co., Ltd."},
    {"1C64", "TRS-RenTelco"},
    {"1DD1", "Truechip Solutions Pvt. Ltd."},
    {"2055", "Tsecond Inc"},
    {"200C", "Tsingmicro Intelligent Technology Co., Ltd."},
    {"189E", "TSMC"},
    {"1C7E", "TTTech Computertechnik AG"},
    {"148C", "Tul Corporation"},
    {"1E32", "Tuxera Inc."},
    {"14FF", "Twinhead International Corporation"},
    {"1962", "U.S. Patent &amp; Trademark Office"},
    {"11559", "UL Solutions"},
    {"18D1", "ULVAC-PHI, Inc."},
    {"19BF", "Unicom Engineering Inc"},
    {"0526", "Unicompute Technology Co., Ltd."},
    {"1FAB", "UniFabriX Ltd."},
    {"1CC2", "Unigen Corp"},
    {"2061", "Unis Flash Memory Technology (Chengdu) Co., Ltd."},
    {"1DB3", "Unisoc (Shanghai) Technologies Co., Ltd."},
    {"1018", "Unisys Corporation"},
    {"2007", "United Micro Technology (Shenzhen) Co. Ltd."},
    {"1DC9", "UniTest"},
    {"1A00", "Universal Audio, Inc."},
    {"14CD", "Universal Global Scientific Industrial Co., Ltd"},
    {"1E67", "Untether AI Corporation"},
    {"1DF8", "V&amp;G Information System Co.,Ltd"},
    {"2028", "VA Linux Systems Japan K.K."},
    {"ABCD", "Vadatech Inc."},
    {"1D19", "VAIO Corporation"},
    {"1E44", "Valve Software"},
    {"1FCB", "Varex Imaging Deutschland AG"},
    {"1E46", "Varjo Technologies Oy"},
    {"1EC6", "Vastai Technologies (Shanghai) Inc"},
    {"1DAE", "Vectology,Inc."},
    {"19E2", "Vector Informatik GmbH"},
    {"1EB1", "VeriSilicon Inc."},
    {"1E9D", "VersaLogic Corporation"},
    {"1106", "VIA Technologies, Inc."},
    {"2034", "ViALUX Messtechnik + Bildverarbeitung GmbH"},
    {"1B83", "Viasat Inc."},
    {"1D7D", "VIAVI Solutions"},
    {"1F9F", "Virtium"},
    {"142E", "VITEC"},
    {"1197", "Vitrek, LLC"},
    {"156C", "VMagic Electronics GmbH"},
    {"1EBF", "Volex Interconnect Systems (Suzhou) Co., Ltd."},
    {"1433", "Westermo Eltec GmbH"},
    {"1B96", "Western Digital Technologies, Inc."},
    {"1E15", "Wieson Technologies Co., LTD."},
    {"2069", "WIKO Terminal Technology(Dongguan)Co., Ltd."},
    {"1CCE", "Wilder Technologies"},
    {"1E75", "Wind River Systems, Inc."},
    {"1EC9", "Wingtech Group(HongKong)Limited"},
    {"1EA8", "Winintec"},
    {"1F38", "Wisewave Technology Co., Ltd"},
    {"17C0", "Wistron Corporation"},
    {"1F48", "Wistron NeWeb Corp."},
    {"1EC1", "Wiwynn Corporation"},
    {"1F05", "WLCO(ShenZhen) Co.,Ltd."},
    {"301F", "WOLF Advanced Technology"},
    {"1F15", "Wolley (Taiwan) Ltd."},
    {"1F32", "Wuhan YuXin Semiconductor Co., Ltd."},
    {"1F19", "Wuxi High Information Security Technology Co. ,Ltd."},
    {"8848", "Wuxi Micro Innovation Integrated Circuit Design Co.,Ltd"},
    {"2047", "Wuxi Ranke Technology Co., Ltd."},
    {"1FE2", "Wuxi Silicon Field Microelectronics Co.,Ltd."},
    {"1EB6", "Wuxi Stars Microsystem Technology Co., Ltd"},
    {"1F16", "Xconn Technologies Holdings, Inc."},
    {"FFE1", "XeL Technology, Inc."},
    {"1F7F", "XEPIC Corporation Limited"},
    {"10C5", "Xerox Corporation"},
    {"1F24", "xFusion Digital Technologies Co., Limited"},
    {"2042", "Xi&#039;an UniIC Semiconductors Co.,Ltd."},
    {"1EED", "Xiangdixian Computing Technology (Chongqing) Limited Company"},
    {"1D72", "Xiaomi Communications Co., Ltd."},
    {"DEDA", "XIMEA"},
    {"1C5B", "XJTAG Ltd."},
    {"1E6C", "Xsight Labs Ltd"},
    {"203B", "XTX Markets Technologies Limited"},
    {"1D93", "YADRO"},
    {"1073", "Yamaha Corporation"},
    {"18B4", "Yamaichi Electronics"},
    {"1E49", "Yangtze Memory Technologies Co.,Ltd"},
    {"1313", "YASKAWA Electric Corporation"},
    {"2019", "Yicun Technology(ShangHai)Co.Ltd"},
    {"1281", "Yokogawa Electric Corporation"},
    {"1F47", "YUSUR Technology Co., Ltd."},
    {"2018", "Zebra Technologies Corporation"},
    {"1FE5", "Zephyr Computing Systems Inc."},
    {"1E21", "ZF Friedrichshafen AG"},
    {"2078", "Zhejiang Speed Memory Co., Ltd."},
    {"205C", "Zhejiang VMing Semiconductor Co., Ltd"},
    {"1E76", "Zhejiang Zhaolong Interconnect Technology Co., Ltd"},
    {"206F", "Zhongke Tenglong Information Technology Co., Ltd"},
    {"201B", "Zhuhai LINKE Technology Co., Ltd."},
    {"1DCF", "Zhuhai Sinead Technology Co., Ltd."},
    {"6899", "ZT Systems"},
    {"1CF2", "ZTE Corporation"}
};

#endif // VENDOR_MAP_HPP
